import { notFound, redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { getCurrentUser } from "@/lib/auth";
import { parseArr } from "@/lib/format";
import { PrintButton } from "@/components/admin/PrintButton";

export const dynamic = "force-dynamic";

function fmt(d: Date | null | undefined) {
  return d ? new Date(d).toLocaleString("en-GB") : "—";
}

export default async function IncidentPrintPage({ params }: { params: { id: string } }) {
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  if (user.role !== "admin") redirect("/dashboard");

  const c = await prisma.case.findUnique({
    where: { id: params.id },
    include: { user: true, incidentReport: true },
  });
  if (!c) notFound();
  const r = c.incidentReport;

  return (
    <div className="section max-w-3xl py-8">
      <div className="mb-6 flex items-center justify-between no-print">
        <a href={`/admin/incidents/${c.id}`} className="text-sm text-brand-700">← Back</a>
        <PrintButton />
      </div>

      <div className="print-area text-slate-900">
        <div className="flex items-center justify-between border-b-2 border-slate-800 pb-3">
          <div>
            <h1 className="text-2xl font-extrabold">Angel Bridge Foundation</h1>
            <p className="text-sm text-slate-500">Incident Report</p>
          </div>
          <div className="text-right text-sm">
            <p className="font-bold">Incident No. {c.caseNumber}</p>
            <p className="text-slate-500">Status: {r?.status === "completed" ? "Completed" : r ? "Draft" : "Not started"}</p>
          </div>
        </div>

        <Block title="Person assisted">
          <Line k="Name" v={c.user.fullName} />
          <Line k="Phone" v={c.user.phone} />
          <Line k="Email" v={c.user.email} />
        </Block>

        <Block title="The request">
          <Line k="Situation" v={c.situationType} />
          <Line k="Reported" v={fmt(c.incidentAt)} />
          <Line k="Location" v={`${c.currentAddress}, ${c.currentPostcode}`} />
          {c.currentLat != null && <Line k="GPS" v={`${c.currentLat.toFixed(5)}, ${c.currentLng?.toFixed(5)}`} />}
          <Line k="Needs" v={parseArr(c.needs).join(", ") + (c.needsOther ? ` (Other: ${c.needsOther})` : "")} />
          {c.shareIdentity && <Line k="Identify by" v={[c.carReg, c.surroundings, c.wearing].filter(Boolean).join(" · ") || "—"} />}
          <Line k="Description" v={c.description} />
        </Block>

        <Block title="Response">
          <Line k="Completed by" v={r?.completedByName || "—"} />
          <Line k="Member email" v={r?.completedByEmail || "—"} />
          <Line k="Arrived" v={fmt(r?.arrivedAt)} />
          <Line k="Completed" v={fmt(r?.completedAt)} />
          <Line k="On arrival" v={r?.summary || "—"} />
          <Line k="Help provided" v={r ? parseArr(r.helpProvided).join(", ") || "—" : "—"} />
          <Line k="Supplies given" v={r?.suppliesGiven || "—"} />
          <Line k="Outcome" v={r?.outcome || "—"} />
        </Block>

        <Block title="Emergency services">
          <Line k="999 called" v={r?.emergencyServicesCalled ? "Yes" : "No"} />
          {r?.emergencyServicesCalled && <Line k="Detail" v={r?.emergencyServicesDetail || "—"} />}
        </Block>

        <Block title="Member notes">
          <p className="text-sm text-slate-700">{r?.memberNotes || "—"}</p>
        </Block>

        <Block title="Feedback from the assisted person">
          {r?.feedbackSubmittedAt ? (
            <>
              <Line k="Rating" v={`${r.feedbackRating}/5`} />
              <Line k="Submitted" v={fmt(r.feedbackSubmittedAt)} />
              <Line k="Comment" v={r.feedbackComment || "—"} />
            </>
          ) : (
            <p className="text-sm text-slate-500">Not yet submitted.</p>
          )}
        </Block>

        <div className="mt-8 border-t border-slate-300 pt-3 text-xs text-slate-400">
          Generated by Angel Bridge Foundation · This document contains personal data, handle in line with UK data protection law.
        </div>
      </div>
    </div>
  );
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-5">
      <h2 className="mb-2 text-sm font-bold uppercase tracking-wide text-slate-500">{title}</h2>
      <div className="space-y-1">{children}</div>
    </div>
  );
}

function Line({ k, v }: { k: string; v: string }) {
  return (
    <div className="grid grid-cols-3 gap-2 text-sm">
      <span className="font-medium text-slate-500">{k}</span>
      <span className="col-span-2 text-slate-800">{v}</span>
    </div>
  );
}
